version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: scikit-learn
    versions:
    - 0.24.1
