name: plangid-ci
on:
  push:
    branches:
      - master
  pull_request: {}
jobs:
  lint-black:
    name: lint (black)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: pip install nox
      - run: nox -e lint_black
  lint-flake8:
    name: lint (flake8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: pip install nox
      - run: nox -e lint_flake8
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8']
    env:
      LANGUAGE_DATASET_PATH: language-dataset/data
    name: test (Python ${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - run: pip install nox
      - run: git clone https://github.com/smola/language-dataset
      - run: nox -e test-${{ matrix.python-version }}
